# Generated by Django 2.0 on 2017-12-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20171228_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, verbose_name='index')),
                ('name', models.CharField(max_length=200, verbose_name='company')),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, verbose_name='index')),
                ('_id', models.CharField(max_length=250, verbose_name='_id')),
                ('has_died', models.BooleanField(verbose_name='has_died')),
                ('age', models.IntegerField(verbose_name='age')),
                ('eyeColor', models.CharField(max_length=50, verbose_name='eyeColor')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('gender', models.CharField(max_length=20, verbose_name='gender')),
                ('email', models.TextField(verbose_name='email')),
                ('phone', models.TextField(verbose_name='phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Company')),
                ('friends', models.ManyToManyField(related_name='_person_friends_+', to='core.Person')),
                ('fruits', models.ManyToManyField(related_name='fruits', to='core.Fruit')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='vegetables',
            field=models.ManyToManyField(related_name='vegetables', to='core.Vegetables'),
        ),
    ]
