# Generated by Django 2.0 on 2017-12-28 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171228_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
        migrations.RemoveField(
            model_name='person',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='person',
            name='fruits',
        ),
        migrations.RemoveField(
            model_name='person',
            name='vegetables',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Vegetables',
        ),
    ]
