# Generated by Django 2.0 on 2017-12-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171228_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
        migrations.RemoveField(
            model_name='person',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='vegetables',
            name='person',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Vegetables',
        ),
    ]
