# Generated by Django 2.0 on 2017-12-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171228_2322'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fruits',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
        migrations.RemoveField(
            model_name='person',
            name='friends',
        ),
        migrations.AlterUniqueTogether(
            name='vegetables',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vegetables',
            name='person',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Fruits',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Vegetables',
        ),
    ]
